image: node:8.10-alpine

pipelines:
  default:
    - step:
        name: Deploy DEV
        deployment: dev
        trigger: manual
        caches:
          - node
          - logGroupCreatorNodeModules
        script:
          - export ENVIRONMENT=dev
          - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_DEV

          - apk add --no-cache py-pip make bash git openssh-client
          - pip install awscli

          - make deploy-dev

    - step:
        name: Deploy TEST
        deployment: test
        trigger: manual
        caches:
          - node
          - logGroupCreatorNodeModules
        script:
          - export ENVIRONMENT=test
          - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY_TEST
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_TEST
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_TEST

          - apk add --no-cache py-pip make bash git openssh-client
          - pip install awscli

          - make deploy-test

    - step:
        name: Deploy PROD
        deployment: prod
        trigger: manual
        script:
          - export ENVIRONMENT=prod
          - export AWS_ACCESS_KEY=$AWS_ACCESS_KEY_ID_PROD
          - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD
          - export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION_PROD

          - apk add --no-cache py-pip make bash git openssh-client
          - pip install awscli

          - make deploy-prod

definitions:
  caches:
    logGroupCreatorNodeModules: ./lambdas/logGroupCreator/node_modules
